on:
  push:
name: action

defaults:
  run:
    working-directory: .

jobs:
  hello-world:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run pytest
        run: python ./src/test.py
